{
 "title": "Mainnet Validator",
 "tags": [
  "solana",
  "validator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "'Mainnet MAIN'" }
   ]
  },
  {
   "title": "Epoch #",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_epoch_info{job=\"solana-validator\"}",
     "legendFormat": "Epoch #"
    }
   ]
  },
  {
   "title": "Ep. progress",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_epoch_progress{job=\"solana-validator\"} * 100",
     "legendFormat": "Progress"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_is_voting{job=\"solana-validator\"}"
    }
   ]
  },
  {
   "title": "Skiprate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_skip_rate{job=\"solana-validator\"}"
    }
   ]
  },
  {
   "title": "Commission",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "100" }
   ]
  },
  {
   "title": "Active stake",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_active_stake{job=\"solana-validator\"} / 1e9",
     "legendFormat": "Active Stake"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_version{job=\"solana-validator\"}"
    }
   ]
  },
  {
   "title": "IO wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node_validator\"}[5m])"
    }
   ]
  },
  {
   "title": "SOL price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_price_usd{job=\"solana-validator\"}"
    }
   ]
  },
  {
   "title": "15m load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{job=\"node_validator\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemAvailable_bytes{job=\"node_validator\"} or node_memory_MemFree_bytes{job=\"node_validator\"}) / node_memory_MemTotal_bytes{job=\"node_validator\"}))"
    }
   ]
  },
  {
   "title": "root",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "home",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/home\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/home\"})"
    }
   ]
  },
  {
   "title": "accounts1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/accounts1\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/accounts1\"})"
    }
   ]
  },
  {
   "title": "accounts2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/accounts2\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/accounts2\"})"
    }
   ]
  },
  {
   "title": "ledger",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/ledger\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/ledger\"})"
    }
   ]
  },
  { "title": "Validator Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Leader Slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "solana_validator_leader_slots_total{job=\"solana-validator\",status=\"valid\"}",
     "legendFormat": "Valid Slots"
    },
    {
     "expr": "solana_validator_leader_slots_total{job=\"solana-validator\",status=\"skipped\"}",
     "legendFormat": "Skipped Slots"
    }
   ]
  },
  {
   "title": "Active Stake (SOL)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_cluster_active_stake{job=\"solana-validator\"} / 1e9",
     "legendFormat": "Active Stake (SOL)"
    }
   ]
  },
  { "title": "Cluster Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_cluster_validator_count{job=\"solana-validator\",state=\"current\"}"
    }
   ]
  },
  {
   "title": "Delinquent Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_cluster_validator_count{job=\"solana-validator\",state=\"delinquent\"}"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{job=\"node_validator\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "node_load1{job=\"node_validator\"}",
     "legendFormat": "1m load"
    },
    {
     "expr": "node_load5{job=\"node_validator\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "node_load15{job=\"node_validator\"}",
     "legendFormat": "15m load"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{job=\"node_validator\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_validator\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_validator\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemUsed_bytes{job=\"node_validator\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "System Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Hardware Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_validator\"}",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "node_procs_blocked{job=\"node_validator\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "node_procs_running{job=\"node_validator\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_paging{job=\"node_validator\"}",
     "legendFormat": "paging"
    },
    {
     "expr": "node_procs_sleeping{job=\"node_validator\"}",
     "legendFormat": "sleeping"
    },
    {
     "expr": "node_procs_stopped{job=\"node_validator\"}",
     "legendFormat": "stopped"
    },
    {
     "expr": "node_procs_zombie{job=\"node_validator\"}",
     "legendFormat": "zombies"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_context_switches_total{job=\"node_validator\"}",
     "legendFormat": "Context switches"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node_validator\",device=~\"enp1s0f1np1|enp6s0\"}[5m]) * 8 / 1000000",
     "legendFormat": "Incoming"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node_validator\",device=~\"enp1s0f1np1|enp6s0\"}[5m]) * 8 / 1000000",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "IP datagrams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{job=\"node_validator\",device=~\"enp1s0f1np1|enp6s0\"}[5m])",
     "legendFormat": "Incoming"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{job=\"node_validator\",device=~\"enp1s0f1np1|enp6s0\"}[5m])",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"node_validator\"}",
     "legendFormat": "Established"
    },
    {
     "expr": "node_netstat_Tcp_Listen{job=\"node_validator\"}",
     "legendFormat": "Listen"
    },
    {
     "expr": "node_netstat_TcpExt_SyncookiesSent{job=\"node_validator\"}",
     "legendFormat": "Syn sent"
    },
    {
     "expr": "node_netstat_TcpExt_SyncookiesRecv{job=\"node_validator\"}",
     "legendFormat": "Syn received"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Disk usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/\"})",
     "legendFormat": "root"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/home\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/home\"})",
     "legendFormat": "home"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/ledger\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/ledger\"})",
     "legendFormat": "ledger"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/accounts1\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/accounts1\"})",
     "legendFormat": "accounts1"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/accounts2\"} * 100) / node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/accounts2\"})",
     "legendFormat": "accounts2"
    }
   ]
  },
  {
   "title": "Disk usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/ledger\"} - node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/ledger\"}",
     "legendFormat": "ledger"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/\"}",
     "legendFormat": "root"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/home\"} - node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/home\"}",
     "legendFormat": "home"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/accounts1\"} - node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/accounts1\"}",
     "legendFormat": "accounts1"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node_validator\",mountpoint=\"/accounts2\"} - node_filesystem_avail_bytes{job=\"node_validator\",mountpoint=\"/accounts2\"}",
     "legendFormat": "accounts2"
    }
   ]
  },
  {
   "title": "I/O queue time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node_validator\"}[5m]) * 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Weighted I/O queue time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{job=\"node_validator\"}[5m]) * 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node_validator\"}[5m]) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Average I/O operation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{job=\"node_validator\"}[5m]) / rate(node_disk_reads_completed_total{job=\"node_validator\"}[5m]) * 1000",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{job=\"node_validator\"}[5m]) / rate(node_disk_writes_completed_total{job=\"node_validator\"}[5m]) * 1000",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "I/O reads per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{job=\"node_validator\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "I/O writes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{job=\"node_validator\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}