{
 "title": "Bitcoin node",
 "description": "local",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "BTC Price in USD",
   "type": "stat",
   "description": "BTC Price from Binance API",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_price_usd", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Difficulty (in Trillions x harder than at genesys)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_difficulty", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_mempool_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool Size (in MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_mempool_bytes / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Since Last Block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_time_since_last_block_seconds / 60",
     "legendFormat": "Time since last block"
    }
   ]
  },
  {
   "title": "Low fee (~6 Blocks) sat/vB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_fee_low", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Medium fee (~3 Blocks) sat/vB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_fee_medium", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "High fee (Next Blocks) sat/vB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_fee_high", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blockchain Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_size_on_disk_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total UTXOs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bitcoin_utxo_count", "legendFormat": " UTXOs" }
   ]
  },
  {
   "title": "UTXO Set size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_utxo_size_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Network Stats",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_connections_inbound", "legendFormat": "Inbound Peers" },
    { "expr": "bitcoin_connections_outbound", "legendFormat": "Outbound Peers" }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(bitcoin_network_bytes_sent_total[5m])",
     "legendFormat": "Upload"
    },
    {
     "expr": "rate(bitcoin_network_bytes_received_total[5m])",
     "legendFormat": "Download"
    }
   ]
  }
 ]
}