{
 "title": "Testnet validator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Validator - chain info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_node_epoch_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Epoch progression",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(solana_node_slot_height - solana_node_epoch_first_slot) / (solana_node_epoch_last_slot - solana_node_epoch_first_slot) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_node_is_healthy", "legendFormat": "Running" },
    { "expr": "solana_validator_delinquent", "legendFormat": "Delinquant" },
    { "expr": "solana_node_num_slots_behind", "legendFormat": "Slots behind" }
   ]
  },
  {
   "title": "Active stake",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_active_stake{nodekey=\"JDa72CkixfF1JD9aYZosWqXyFCZwMpnVjR15bVBW2QRF\"}",
     "legendFormat": "Validator Active Stake %"
    }
   ]
  },
  {
   "title": "Skip rate",
   "type": "timeseries",
   "description": "The rate of skipped leader slots as a percentage. This is a critical metric for validator performance, as high skip rates can indicate issues with the validator's ability to produce blocks when it's assigned to do so.\nCheck with command:\nsolana validators | grep JDa72CkixfF1JD9aYZosWqXyFCZwMpnVjR15bVBW2QRF\n\nData gaps are generally periods where our validator has no assigned leader slot.\n\nCheck schedule for this epoch with:\nsolana leader-schedule | grep JDa72CkixfF1JD9aYZosWqXyFCZwMpnVjR15bVBW2QRF\n\nThen compare to current slot.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(solana_validator_leader_slots_total{nodekey=\"JDa72CkixfF1JD9aYZosWqXyFCZwMpnVjR15bVBW2QRF\",status=\"skipped\"}[5m])",
     "legendFormat": "Validator Skip Rate"
    },
    {
     "expr": "(\r\n  sum(rate(solana_validator_leader_slots_total{status=\"skipped\"}[5m]))\r\n  /\r\n  sum(rate(solana_validator_leader_slots_total{}[5m]))\r\n) * 100",
     "legendFormat": "Cluster's average Skip rate"
    }
   ]
  },
  {
   "title": "System metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Hardware metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "Network Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  }
 ]
}